const playerStorage = {
	// uncooked fish
	'raw crawfish': 1,
	'raw bluegill': 0,
	'raw crappie': 0,
	'raw lava shrimp': 0,
	'raw cod': 0,
	'raw salmon': 0,
	'raw white ray': 0,
	'raw lobster': 0,
	'raw shadowfin': 0,
	'raw swordfish': 0,
	'raw goliath tigerfish': 0,
	'raw magma grouper': 0,
	'raw glacial monkfish': 0,

	// cooked fish
	'crawfish': 0,
	'bluegill': 0,
	'crappie': 0,
	'lava shrimp': 0,
	'cod': 0,
	'salmon': 0,
	'white ray': 0,
	'lobster': 0,
	'shadowfin': 0,
	'swordfish': 0,
	'goliath tigerfish': 0,
	'magma grouper': 0,
	'glacial monkfish': 0,

	// minerals
	'copper': 0,
	'tin': 0,
	'iron': 0,
	'silver': 0,
	'coal': 0,
	'enchanted stone': 0,
	'gold': 0,
	'adamant': 0,
	'blessed crystal': 0,
	'starcore': 0,
	'dragonscale': 0,
	'magmaheart': 0,
	'aegis stone': 0,
	'maelstromite': 0,

	// metals
	'bronze': 0,
	'iron': 0,
	'silver': 0,
	'steel': 0,
	'enchanted stone': 0,
	'gold': 0,
	'adamant': 0,
	'blessed crystal': 0,
	'dragonscale': 0,
	'magmaheart': 0,
	'aegis stone': 0,
	'maelstromite': 0,

	// wood
	'fir': 0,
	'pine': 0,
	'oak': 0,
	'maple': 0,
	'cherry': 0,
	'ironwood': 0,
	'glimmering': 0,
}

export default playerStorage;