const playerStorage = {
	// uncooked fish
	'raw crawfish': 0,
	'raw bluegill': 0,
	'raw crappie': 0,
	'raw lava shrimp': 0,
	'raw cod': 0,
	'raw salmon': 0,
	'raw white ray': 0,
	'raw lobster': 0,
	'raw shadowfin': 0,
	'raw swordfish': 0,
	'raw goliath tigerfish': 0,
	'raw magma grouper': 0,
	'raw glacial monkfish': 0,

	// cooked fish
	'crawfish': 0,
	'bluegill': 0,
	'crappie': 0,
	'lava shrimp': 0,
	'cod': 0,
	'salmon': 0,
	'white ray': 0,
	'lobster': 0,
	'shadowfin': 0,
	'swordfish': 0,
	'goliath tigerfish': 0,
	'magma grouper': 0,
	'glacial monkfish': 0,

	// minerals
	'copper ore': 0,
	'tin ore': 0,
	'iron ore': 0,
	'silver ore': 0,
	'coal ore': 0,
	'enchanted stone': 0,
	'gold ore': 0,
	'adamant ore': 0,
	'blessed crystal': 0,
	'starcore': 0,
	'dragonscale': 0,
	'magmaheart ore': 0,
	'aegis stone': 0,
	'maelstromite ore': 0,

	// metals
	'bronze bar': 0,
	'iron bar': 0,
	'silver bar': 0,
	'steel bar': 0,
	'enchanted bar': 0,
	'gold bar': 0,
	'adamant bar': 0,
	'blessed bar': 0,
	'dragonscale bar': 0,
	'magmaheart bar': 0,
	'aegis bar': 0,
	'maelstrom bar': 0,

	// wood
	'fir log': 0,
	'pine log': 0,
	'oak log': 0,
	'maple log': 0,
	'cherry log': 0,
	'ironwood log': 0,
	'glimmering log': 0,
}

export default playerStorage;