const fishingData = [
	{
		name: 'crawfish',
		skill: 'fishing',
		minLevel: 1,
		experience: 1,
		attemptRate: 2300,
		successRate: 80,
		depleteChance: 30,
	},
	{
		name: 'bluegill',
		skill: 'fishing',
		minLevel: 5,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'crappie',
		skill: 'fishing',
		minLevel: 10,
		experience: 1,
		attemptRate: 500,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'lava shrimp',
		skill: 'fishing',
		minLevel: 15,
		experience: 1,
		attemptRate: 5000,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'cod',
		skill: 'fishing',
		minLevel: 25,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'salmon',
		skill: 'fishing',
		minLevel: 30,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'white ray',
		skill: 'fishing',
		minLevel: 40,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'lobster',
		skill: 'fishing',
		minLevel: 45,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'shadowfin',
		skill: 'fishing',
		minLevel: 60,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'swordfish',
		skill: 'fishing',
		minLevel: 70,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'goliath tigerfish',
		skill: 'fishing',
		minLevel: 80,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'magma grouper',
		skill: 'fishing',
		minLevel: 90,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
	{
		name: 'glacial monkfish',
		skill: 'fishing',
		minLevel: 95,
		experience: 1,
		attemptRate: 2300,
		successRate: 50,
		depleteChance: 30,
	},
]

export default fishingData;