const fishingData = [
	{
		name: 'crawfish',
		skill: 'fishing',
		minLevel: 1,
		experience: 9,
		attemptRate: 2300,
		successRate: 55,
		depleteChance: 50,
	},
	{
		name: 'bluegill',
		skill: 'fishing',
		minLevel: 5,
		experience: 40,
		attemptRate: 2500,
		successRate: 30,
		depleteChance: 30,
	},
	{
		name: 'crappie',
		skill: 'fishing',
		minLevel: 10,
		experience: 95,
		attemptRate: 2600,
		successRate: 20,
		depleteChance: 30,
	},
	{
		name: 'lava shrimp',
		skill: 'fishing',
		minLevel: 15,
		experience: 215,
		attemptRate: 2700,
		successRate: 15,
		depleteChance: 30,
	},
	{
		name: 'cod',
		skill: 'fishing',
		minLevel: 25,
		experience: 333,
		attemptRate: 2900,
		successRate: 20,
		depleteChance: 10,
	},
	{
		name: 'salmon',
		skill: 'fishing',
		minLevel: 30,
		experience: 410,
		attemptRate: 3100,
		successRate: 25,
		depleteChance: 10,
	},
	{
		name: 'white ray',
		skill: 'fishing',
		minLevel: 40,
		experience: 685,
		attemptRate: 3300,
		successRate: 25,
		depleteChance: 15,
	},
	{
		name: 'lobster',
		skill: 'fishing',
		minLevel: 45,
		experience: 999,
		attemptRate: 3400,
		successRate: 20,
		depleteChance: 20,
	},
	{
		name: 'shadowfin',
		skill: 'fishing',
		minLevel: 60,
		experience: 1025,
		attemptRate: 3600,
		successRate: 35,
		depleteChance: 30,
	},
	{
		name: 'swordfish',
		skill: 'fishing',
		minLevel: 70,
		experience: 1337,
		attemptRate: 3700,
		successRate: 40,
		depleteChance: 50,
	},
	{
		name: 'goliath tigerfish',
		skill: 'fishing',
		minLevel: 80,
		experience: 1996,
		attemptRate: 4000,
		successRate: 35,
		depleteChance: 40,
	},
	{
		name: 'magma grouper',
		skill: 'fishing',
		minLevel: 90,
		experience: 2850,
		attemptRate: 4200,
		successRate: 30,
		depleteChance: 10,
	},
	{
		name: 'glacial monkfish',
		skill: 'fishing',
		minLevel: 95,
		experience: 3375,
		attemptRate: 4300,
		successRate: 30,
		depleteChance: 20,
	},
]

export default fishingData;