const fishingData = [
	{
		name: 'crawfish',
		skill: 'fishing',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'bluegill',
		skill: 'fishing',
		minLevel: 5,
		experience: 20,
		attemptRate: 1600,
		successRate: 60,
		depleteChance: 25,
	},
	{
		name: 'crappie',
		skill: 'fishing',
		minLevel: 10,
		experience: 35,
		attemptRate: 1900,
		successRate: 85,
		depleteChance: 70,
	},
	{
		name: 'lava shrimp',
		skill: 'fishing',
		minLevel: 15,
		experience: 50,
		attemptRate: 1900,
		successRate: 40,
		depleteChance: 40,
	},
	{
		name: 'cod',
		skill: 'fishing',
		minLevel: 25,
		experience: 70,
		attemptRate: 2000,
		successRate: 60,
		depleteChance: 50,
	},
	{
		name: 'salmon',
		skill: 'fishing',
		minLevel: 30,
		experience: 90,
		attemptRate: 2000,
		successRate: 50,
		depleteChance: 80,
	},
	{
		name: 'white ray',
		skill: 'fishing',
		minLevel: 40,
		experience: 105,
		attemptRate: 2200,
		successRate: 30,
		depleteChance: 20,
	},
	{
		name: 'lobster',
		skill: 'fishing',
		minLevel: 45,
		experience: 120,
		attemptRate: 2300,
		successRate: 70,
		depleteChance: 60,
	},
	{
		name: 'shadowfin',
		skill: 'fishing',
		minLevel: 60,
		experience: 175,
		attemptRate: 2500,
		successRate: 60,
		depleteChance: 45,
	},
	{
		name: 'swordfish',
		skill: 'fishing',
		minLevel: 70,
		experience: 210,
		attemptRate: 2700,
		successRate: 45,
		depleteChance: 30,
	},
	{
		name: 'goliath tigerfish',
		skill: 'fishing',
		minLevel: 80,
		experience: 235,
		attemptRate: 3100,
		successRate: 35,
		depleteChance: 10,
	},
	{
		name: 'magma grouper',
		skill: 'fishing',
		minLevel: 90,
		experience: 390,
		attemptRate: 3400,
		successRate: 70,
		depleteChance: 70,
	},
	{
		name: 'glacial monkfish',
		skill: 'fishing',
		minLevel: 95,
		experience: 465,
		attemptRate: 3700,
		successRate: 65,
		depleteChance: 40,
	},
]

export default fishingData;