const huntingData = [
	{
		name: 'common rabbit',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'pheasant',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'coyote',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'snowshoe hare',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'turkey',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'imp',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'red fox',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'wicked crow',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'ravenous coyote',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'silver fox',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'molten chicken',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'great wolf',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'gryphon',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'shadow imp',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'ashen coyote',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'dwarf dragon',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'star wolf',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
	{
		name: 'solar gryphon',
		skill: 'hunting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
		resourceMin: 1,
		resourceMax: 1,
	},
]

export default huntingData;