const huntingData = [
	{
		name: 'common rabbit',
		skill: 'hunting',
		minLevel: 1,
		experience: 7,
		attemptRate: 2000,
		successRate: 40,
		depleteChance: 50,
	},
	{
		name: 'pheasant',
		skill: 'hunting',
		minLevel: 5,
		experience: 23,
		attemptRate: 2300,
		successRate: 20,
		depleteChance: 30,
	},
	{
		name: 'snowshoe hare',
		skill: 'hunting',
		minLevel: 9,
		experience: 65,
		attemptRate: 2000,
		successRate: 10,
		depleteChance: 30,
	},
	{
		name: 'turkey',
		skill: 'hunting',
		minLevel: 12,
		experience: 135,
		attemptRate: 3700,
		successRate: 18,
		depleteChance: 45,
	},
	{
		name: 'imp',
		skill: 'hunting',
		minLevel: 15,
		experience: 333,
		attemptRate: 1100,
		successRate: 3,
		depleteChance: 10,
	},
	{
		name: 'red fox',
		skill: 'hunting',
		minLevel: 20,
		experience: 235,
		attemptRate: 6000,
		successRate: 25,
		depleteChance: 15,
	},
	{
		name: 'wicked crow',
		skill: 'hunting',
		minLevel: 24,
		experience: 350,
		attemptRate: 5400,
		successRate: 25,
		depleteChance: 15,
	},
	{
		name: 'ravenous coyote',
		skill: 'hunting',
		minLevel: 32,
		experience: 630,
		attemptRate: 6500,
		successRate: 20,
		depleteChance: 30,
	},
	{
		name: 'silver fox',
		skill: 'hunting',
		minLevel: 40,
		experience: 2666,
		attemptRate: 8500,
		successRate: 8,
		depleteChance: 35,
	},
	{
		name: 'molten chicken',
		skill: 'hunting',
		minLevel: 46,
		experience: 1337,
		attemptRate: 6400,
		successRate: 15,
		depleteChance: 40,
	},
	{
		name: 'great wolf',
		skill: 'hunting',
		minLevel: 55,
		experience: 1130,
		attemptRate: 6500,
		successRate: 30,
		depleteChance: 30,
	},
	{
		name: 'gryphon',
		skill: 'hunting',
		minLevel: 65,
		experience: 2450,
		attemptRate: 9000,
		successRate: 25,
		depleteChance: 5,
	},
	{
		name: 'shadow imp',
		skill: 'hunting',
		minLevel: 70,
		experience: 666,
		attemptRate: 1300,
		successRate: 17,
		depleteChance: 10,
	},
	{
		name: 'ashen coyote',
		skill: 'hunting',
		minLevel: 75,
		experience: 2063,
		attemptRate: 7500,
		successRate: 35,
		depleteChance: 35,
	},
	{
		name: 'dwarf dragon',
		skill: 'hunting',
		minLevel: 85,
		experience: 11500,
		attemptRate: 17500,
		successRate: 20,
		depleteChance: 40,
	},
	{
		name: 'star wolf',
		skill: 'hunting',
		minLevel: 92,
		experience: 4750,
		attemptRate: 11500,
		successRate: 35,
		depleteChance: 30,
	},
	{
		name: 'solar gryphon',
		skill: 'hunting',
		minLevel: 95,
		experience: 22750,
		attemptRate: 20000,
		successRate: 15,
		depleteChance: 5,
	},
]

export default huntingData;