const miningData = [
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 7,
		attemptRate: 1500,
		successRate: 45,
		depleteChance: 40,
	},
	{
		name: 'tin',
		skill: 'mining',
		minLevel: 3,
		experience: 12,
		attemptRate: 1700,
		successRate: 40,
		depleteChance: 40,
	},
	{
		name: 'iron',
		skill: 'mining',
		minLevel: 15,
		experience: 50,
		attemptRate: 2200,
		successRate: 50,
		depleteChance: 20,
	},
	{
		name: 'silver',
		skill: 'mining',
		minLevel: 20,
		experience: 115,
		attemptRate: 2500,
		successRate: 50,
		depleteChance: 60,
	},
	{
		name: 'coal',
		skill: 'mining',
		minLevel: 25,
		experience: 70,
		attemptRate: 1600,
		successRate: 80,
		depleteChance: 50,
	},
	{
		name: 'enchanted stone',
		skill: 'mining',
		minLevel: 40,
		experience: 540,
		attemptRate: 3200,
		successRate: 35,
		depleteChance: 10,
	},
	{
		name: 'gold',
		skill: 'mining',
		minLevel: 45,
		experience: 733,
		attemptRate: 2500,
		successRate: 25,
		depleteChance: 70,
	},
	{
		name: 'adamant',
		skill: 'mining',
		minLevel: 50,
		experience: 700,
		attemptRate: 3300,
		successRate: 45,
		depleteChance: 40,
	},
	{
		name: 'blessed crystal',
		skill: 'mining',
		minLevel: 60,
		experience: 1080,
		attemptRate: 3900,
		successRate: 40,
		depleteChance: 45,
	},
	{
		name: 'starcore',
		skill: 'mining',
		minLevel: 65,
		experience: 554,
		attemptRate: 3100,
		successRate: 75,
		depleteChance: 85,
	},
	{
		name: 'dragonscale',
		skill: 'mining',
		minLevel: 70,
		experience: 1555,
		attemptRate: 4100,
		successRate: 40,
		depleteChance: 15,
	},
	{
		name: 'magmaheart',
		skill: 'mining',
		minLevel: 75,
		experience: 1776,
		attemptRate: 4200,
		successRate: 40,
		depleteChance: 20,
	},
	{
		name: 'aegis stone',
		skill: 'mining',
		minLevel: 80,
		experience: 2100,
		attemptRate: 2650,
		successRate: 25,
		depleteChance: 35,
	},
	{
		name: 'maelstromite',
		skill: 'mining',
		minLevel: 90,
		experience: 2575,
		attemptRate: 4500,
		successRate: 40,
		depleteChance: 30,
	},
]

export default miningData;