const miningData = [
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'tin',
		skill: 'mining',
		minLevel: 2,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'iron',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'silver',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'coal',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'enchanted stone',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
]

export default miningData;