const miningData = [
	{
		name: 'copper',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'tin',
		skill: 'mining',
		minLevel: 2,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'iron',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'silver',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'coal',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'enchanted stone',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'gold',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'adamant',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'blessed crystal',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'starcore',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'dragonscale',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'magmaheart',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'aegis stone',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
	{
		name: 'maelstromite',
		skill: 'mining',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 65,
		depleteChance: 20,
	},
]

export default miningData;