const woodcuttingData = [
	{
		name: 'fir',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'pine',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'oak',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'maple',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'cherry',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'ironwood',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
	{
		name: 'glimmering',
		skill: 'woodcutting',
		minLevel: 1,
		experience: 12,
		attemptRate: 1500,
		successRate: 100,
		depleteChance: 20,
	},
]

export default woodcuttingData;